### ISSUE TITLE
Better example of the configuration

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-atto_styles#1]
I was thinking that something like the following might work better as the default / example configuration. As many sites are using a bootstrap-based theme, it will immediately work for them without the need to customize their theme.

```
{
    "title": "Hero unit box",
    "type": "block",
    "classes": "hero-unit"
},{
    "title": "Well",
    "type": "block",
    "classes": "well"
},{
    "title": "Info text",
    "type": "inline",
    "classes": "label label-info"
},{
    "title": "Warning text",
    "type": "inline",
    "classes": "label label-warning"
}
```

These are just standard CSS class from
http://getbootstrap.com/2.3.2/components.html that I found useful in
these cases.

**Comment by abias** [comment]
Hi David,

thanks for this suggestion! 

I have adopted your proposal in 907cd61a2041c59f209760cc0763955f0c642c2e.

Thanks,
Alex
