### ISSUE TITLE
Quotes not escaping properly in 3.5

### ISSUE THREAD

**Issue by hamboneZA** [moodleuulm/moodle-atto_styles#13]
Folks, thanks for a really useful plugin. I'm attempting to create a multilang span class using this tool, with this:

`{
    "title": "LANG: EN",
    "type": "inline",
    "classes": "\"multilang\" lang=\"en\""
},`

Then when I use the editor, highlight some text, and choose the style I get this:
`<span class="&quot;multilang&quot; lang=&quot;en&quot;">TEXT IN ENGLISH</span>`

This is obviously not what I wanted to achieve since it would appear the additional quotes aren't being escaped. Could someone point me in the right direction as to what I might be doing wrong?

**Comment by abias** [comment]
Hi @hamboneZA ,

I am sorry to disappoint you, but this plugin is there to add class attributes to markup elements (span / div) and nothing else. 

Even if your configuration which you quoted above would work and would add the lang attribute correctly, it would have to be considered as hack and nobody will guarantee that the lang attribute will survive all subsequent change operations of atto_styles.

Here are some other Atto plugins which might help you to achieve what you want to do:
https://moodle.org/plugins/atto_multilang2
https://moodle.org/plugins/atto_generico
https://moodle.org/plugins/atto_snippet
https://moodle.org/plugins/atto_templates

Cheers,
Alex

**Comment by hamboneZA** [comment]
Appreciate the feedback @abias :)
