### ISSUE TITLE
Can't get a preview of the styles in Atto

### ISSUE THREAD

**Issue by nickvarney** [moodleuulm/moodle-atto_styles#17]
Running Moodle 3.5 and v3.5-r2 of atto styles. The drop-down menu in the Atto editor does not display a preview of the styles. Instead it displays '</> name of style'.

Has the preview function become deprecated? 
I have "preview": "true" set for each style in the Styles settings page. However your example code on that page omits this line.

**Comment by abias** [comment]
Hi @nickvarney ,

I am sorry to tell you that the preview function has been added to the 3.6 version of the plugin (see https://github.com/moodleuulm/moodle-atto_styles/blob/master/CHANGES.md#v36-r1) and won't be backported to older versions (see https://github.com/moodleuulm/moodle-atto_styles/blob/master/README.md#moodle-release-support).

The only thing which you can do is to backport the latest version yourself as described on https://github.com/moodleuulm/moodle-atto_styles/blob/master/README.md#moodle-release-support. For backporting the 3.7 version to 3.5, I don't see fundamental obstacles.

Cheers,
Alex
