### ISSUE TITLE
Plans for Grid support?

### ISSUE THREAD

**Issue by dirkca** [moodleuulm/moodle-atto_styles#19]
Hello.
I am curious if there are plans to include ability to build layout (columns and rows) Thank you.

**Comment by abias** [comment]
Hey @dirkca ,

thanks for raising this question.
However, I don't think that we will be able and should add any layout support to this plugin. Grid support will need much more thought and functionality than this rather simple plugin and its style-dropdown is providing.

You might want to look at https://moodle.org/plugins/atto_bsgrid (which is rather outdated, unfortunately) or https://moodle.org/plugins/atto_generico (which can be used for building some layouts) as your next steps.

Cheers,
Alex

**Comment by dirkca** [comment]
Thank you for your reply.

Your atto_styles plugin has been instrumental in raising the overall quality of many of our courses considerable. We are a K-12 school division and our teachers enjoy putting some color and highlighting into their books tremendously without breaking formatting.

**Comment by abias** [comment]
Thank you, @dirkca !
I am proud that your school division benefits from our work :)
