### ISSUE TITLE
 Moodle 3.9 version?

### ISSUE THREAD

**Issue by jarvil1** [moodleuulm/moodle-atto_styles#21]
Hello,

When is Moodle 3.9 version going to be released? @Kathrin84

**Comment by abias** [comment]
Hi @Urpokarhu1 ,

I am sorry that this issue remained unanswered for so long.

This plugin was orphaned und unupdated for about two years, but according to our inforamation the v3.8 release should have always worked even on never Moodle versions.

We are now in the process of releasing new releases up to Moodle 4.0, so you should see updates in your Moodle installation soon.

Cheers,
Alex
