### ISSUE TITLE
[3.2] No style/undefined?

### ISSUE THREAD

**Issue by jaybird440** [moodleuulm/moodle-atto_styles#22]
I set up my install with the CSS and styles widget examples provided in the readme (https://github.com/moodleuulm/moodle-atto_styles/blob/master/README.md) with the CSS pasted into Boost Raw initial SCSS (Site Administration-Appearance-Themes-Boost-Advanced settings) and the styles configuration pasted into the styles settings, and I've added Styles to the Atto toolbar. I have also tried pasting CSS into Boost Raw SCSS as well as the other custom CSS areas available within Themes.

However when I try to edit a page and use Styles this is the result I see:
![image](https://user-images.githubusercontent.com/20949443/104084291-d6691800-5213-11eb-8620-2f39191a0a63.png)

Could you let me know what I may be doing wrong here? Thanks!

**Comment by abias** [comment]
Hi @jaybird440 

first, please note that we don't support Moodle 3.2 anymore at all with this plugin - see https://github.com/moodleuulm/moodle-atto_styles/blob/master/README.md#moodle-release-support for details.

If you really really want to run this plugin on 3.2, you have to use the Moodle 3.2 version of this plugin as well. And if you want to use the examples from https://github.com/moodleuulm/moodle-atto_styles/blob/master/README.md#2-configure-styles-widget, you have to remove the square brackets from the beginning and the end of JSON code. The example is for contemporary versions of this plugin and these quare brackets were not necessary for 3.2.

Good luck,
Alex
