### ISSUE TITLE
[Moodle 3.9.7] [Firefox] Selecting a block style without focussing the editor first applies the style outside the editor

### ISSUE THREAD

**Issue by danowar2k** [moodleuulm/moodle-atto_styles#24]
It seems in Moodle 3.9.7 on Firefox (Chrome and Edge do not have this bug) the document focus isn't set inside the atto editor at the beginning.
When I then select a block style, it is applied outside the editor (e.g. make the page background yellow).

Maybe `element = window.getSelection().focusNode;` isn't the way to go here? Couldn't you work with the "host" or fetch the "editor"? Or you could doublecheck whether the element is one inside the current editor?

**Comment by danowar2k** [comment]
Okay, https://github.com/moodleuulm/moodle-atto_styles/pull/26 should do the trick.

**Comment by abias** [comment]
Solved in #26
