### ISSUE TITLE
TinyMCE 6 plugin

### ISSUE THREAD

**Issue by haietza** [moodleuulm/moodle-atto_styles#32]
Moodle has updated their WYSIWYG editor TinyMCE and will be making that the default in the future: https://tracker.moodle.org/browse/MDL-75071.

Would you consider writing a TinyMCE version of the Styles plugin?

**Comment by abias** [comment]
Thank you for asking, @haietza .
Currently, there is no real plan on our roadmap to build a Tiny plugin. But it is our goal as well to see this functionality in Tiny as well.
