### ISSUE TITLE
Adding 2 classes for inline styling fails on Moodle 3.0.x

### ISSUE THREAD

**Issue by clementpr** [moodleuulm/moodle-atto_styles#4]
Hi,

I use this plug-in with 2 Moodle and the same settings to custom CSS classes to block and inline text.
- With Moodle 2.9.2, everything works well.
- With Moodle 3.0.2, I discover this bug. 
  In "Styles configuration", if I use "inline" with a class in two words with a blank space (example : "h4 myword"), it's impossible to apply the style with Atto. 

`{
    "title": "Title 1",
    "type": "inline",
    "classes": "h3 myclass"
}` = Doesn't work

If I use "inline" with a class in one word (without blank space, example "h4-myword"), I can apply the style with Atto.
`{
    "title": "Title 1",
    "type": "inline",
    "classes": "h3-myclass"
}` = OK

Best regards.

**Comment by abias** [comment]
Hi clementpr,

thanks for raising this issue.

I was able to reproduce the problem. Steps to reproduce:

Configure the plugin as follows:

```
{
    "title": "Block 1 class",
    "type": "block",
    "classes": "class1"
},
{
    "title": "Block 2 classes",
    "type": "block",
    "classes": "class1 class2"
},
{
    "title": "Inline 1 class",
    "type": "inline",
    "classes": "class1"
},
{
    "title": "Inline 2 classes",
    "type": "inline",
    "classes": "class1 class2"
}
```

On Moodle 2.9.4+ all styles can be applied cleanly.
On Moodle 3.0.2+, the style "Inline 2 classes" can't be applied. The atto_styles dropdown freezes and there is a message in the javascript console saying:

> Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('klasse1 klasse2') contains HTML space characters, which are not valid in tokens.

Clementpr, I will try to have this solves as soon as possible, but it might take some time as we are busy updating to 3.0 ourselves.

Sorry,
Alex

**Comment by abias** [comment]
Thanks clementpr for reporting and thanks Davo for the fix!

New version with fix pushed to Github and Moodle plugin repo.

**Comment by clementpr** [comment]
Hi, 
Thank to fix them. I just test this update and it works like a charm.

Best regards.
