### ISSUE TITLE
Requires Moodle 3.1

### ISSUE THREAD

**Issue by haietza** [moodleuulm/moodle-atto_styles#8]
If there were no functionality changes between 6f8c11f and 9805ef0, why does the plugin now require Moodle 3.1? We are currently running 3.0 and would like to be able to use this plugin and any updates until we upgrade to 3.1.

**Comment by abias** [comment]
Hi haietza,

thanks for asking. I understand that the version requirement may be annoying to you, but saving us support time by strictly limiting the number of supported Moodle versions to the latest version is the only way for us to provide our plugins to the community.

You are free to download the latest version, remove the "requires" line from version.php and use the plugin in legacy versions of Moodle at your own risk.

Thanks,
Alex
